### PR TITLE
Allow cli script

### PR DESCRIPTION
**Pull request by zozoh94**
It allows for example to create script for upgrading all packages (using ajax editor).

### CODE REVIEW

**Comment by thomasmars** [comment]
Can you explain what this does ? As far as I can see from the code it will return false if not run as a CLI_SCRIPT, so the behavior is the same as before ?

**Comment by zozoh94** [comment]
Yes maybe it can be useful for others. I develop a script to upgrade with CLI all the H5P libraries. If you are interested I can post it here.

**Comment by zozoh94** [comment]
Someone known why checks failed ?

**Comment by thomasmars** [comment]
I assume it is because the commit this was forked from was failing. If you merge in the latest changes from stable the checks should pass.

**Comment by thomasmars** [comment]
Sorry, currently we're not seeing much interest for such a feature and don't want to introduce unnecessary complexity. Scripts for doing H5P activities will for now have to be extracted and run independent of the plugin and core. Sorry.

**Pull request closed without merging**
