### PR TITLE
Fixed invalid chmod call

### PR DESCRIPTION
**Pull request by marsh0lion**

### CODE REVIEW

**Comment by marsh0lion** [comment]
This should fix #472

**Comment by ing-andres-lopez** [comment]
This patch works perfectly.
https://github.com/h5p/moodle-mod_hvp/pull/472/commits/c64aaae370212bc0bda2a6fdc6d5c1187ce318a5

**Comment by meierwitt** [comment]
Yes, this works for me with Moodle 4.1 and PHP 8.0, 8.1 and 8.2

Thanks, Frank

**Review by duranchen — COMMENTED** [review]
this fix works on my site

**Pull request merged**
