### PR TITLE
Fix #236 add userlist privacy classes.

### LINKED ISSUE #236: Userlist provider missing
The current Moodle versions have 2 additional GDPR functions: get_users_in_context & delete_data_for_users

See https://docs.moodle.org/dev/Privacy_API

### PR DESCRIPTION
**Pull request by danmarsden**
this hasn't been tested very well, but might work - we'll do some internal testing on this too and let you know if we have any issues.

This should fix failing unit tests on Moodle 3.7

### CODE REVIEW

**Comment by golenkovm** [comment]
Hi @thomasmars 
Could you, please, provide ETA for this PR?
Thank you so much.

**Comment by thomasmars** [comment]
I don't have an ETA for this, you can follow and comment on the issue at https://h5ptechnology.atlassian.net/browse/HFP-2553.

**Comment by Peterburnett** [comment]
Hi all,

Could this PR be revisited at any point? In Moodle 3.9 this is a hard test failure, and it would be great to get this resolved.

**Comment by golenkovm** [comment]
Hey, it's been almost 2 years since #236 raised and more than a year since the patch was suggested.

**Comment by alexmorrisnz** [comment]
@thomasmars  can we get an update on when this will be merged?

**Comment by yao9394** [comment]
@thomasmars any update on this please?

**Comment by thomasmars** [comment]
Thanks for the pull request and your patience. Sorry that it has taken so long.

**Pull request merged**
