### PR TITLE
Implementation of core_calendar notifications

### PR DESCRIPTION
**Pull request by ndunand**
see my post in H5P forums at https://h5p.org/node/121088

### CODE REVIEW

**Comment by timothyylim** [comment]
Well done, @ndunand! I've made an issue [here](https://h5ptechnology.atlassian.net/browse/HFP-1550) for it to be reviewed.

**Comment by ndunand** [comment]
Thanks @timothyylim . I've pushed a second commit to better support older Moodle versions.

**Comment by ndunand** [comment]
Hi @timothyylim . Any news on this?

**Comment by timothyylim** [comment]
Hi @ndunand , it appears to be in the backlog and it will probably be part of a coming release but I will try to get it expedited.

**Comment by ndunand** [comment]
Hi @timothyylim thanks! Let me know if there's anything else I can do.

**Comment by ndunand** [comment]
Hi @timothyylim it looks like this has not been included in the latest release (`2018053100`), is this still in the backlog?

**Comment by timothyylim** [comment]
Seems like it's still in the backlog: 

https://h5ptechnology.atlassian.net/browse/HFP-1550

I'll raise it up with the Core Team and try to get it a higher priority

**Comment by thomasmars** [comment]
Great work, thanks. Sorry for the late review and merge.

**Pull request merged**
