### PR TITLE
Fix error or embedding content

### PR DESCRIPTION
**Pull request by melnox**
Fix error "Exception - Too few arguments to function page_requirements_manager::js_call_amd(), 1 passed in [dirroot]/mod/hvp/embed.php on line 94 and at least 2 expected" when attempting to embed and iframe

### CODE REVIEW

**Comment by thomasmars** [comment]
Hi, which Moodle version are you running ? Only one arg should be needed from version 3.9 and onwards which is the earliest still supported version by Moodle: https://docs.moodle.org/dev/Releases.
There is no 'init' function in embed.js.

**Comment by melnox** [comment]
Hi, thanks for the feedback. We are installing this on a Totara 12 which has a base moodle version of 3.3 which is unfortunate. Will there be a version maintained for older versions of Moodle going forward?

Thanks

**Comment by thomasmars** [comment]
Ideally we want to support all Moodle versions, but when they have breaking changes we focus on the versions that are currently supported: https://docs.moodle.org/dev/Releases. I'd imagine it would be in Totara's interest to be compatible with the Moodle interfaces so plugins for Moodle works there as well.
Either way, I'd be happy to accept a pull request that implements support for older versions. I think you'd be able to achieve this by adding a 'init' function within embed.js that is called.

**Comment by melnox** [comment]
Apologies for the late reply. I will look into doing that over the next few days thanks.

**Comment by danowar2k** [comment]
You should really update your version.php then, because in there you say this plugin only needs Moodle 2.6 

https://github.com/h5p/moodle-mod_hvp/blob/326284c7f122b5bd17383a3cc836057f8e78f702/version.php#L27

https://docs.moodle.org/dev/Releases

We've updated to your version and are still using Moodle 3.5 (updating soon), but now embeds break.

**Comment by mgancarzdsi** [comment]
Seconding this, we updated to h5p mod version 1.22.3 in our Moodle 3.5 (also updating soon) since it was indicated as compatible, but now we need to roll back the hvp plugin version because of this breaking change.

**Pull request closed without merging**
